.TH "coordinates_system" 3 "Tue Jul 30 2013" "Version 1.02" "ezLCD Python Module" \" -*- nroff -*-
.ad l
.nh
.SH NAME
coordinates_system \- Introduction To The Coordinates System 
  
.PP
The ezLCD uses a X Y coordinates system to specify the location for all graphics commands \&.
.br
 \fBOne thing to note is that the displays X Y start at 0, so even though you have a display that is 480x272 pixels wide XMAX is 479 and YMAX is 271\&.\fP
.br
 X direction is horizontal across the display starting at the left 0 and ending at the max width of the display\&.
.br
 Y direction is vertical starting at the top 0 and ending at the bottom of the display\&. 
.br
.PP
XMAX and YMAX Values for the ezLCD 3xx Line
.br
 arLCD 319 239
.br
 ezLCD-301 399 239
.br
 ezLCD-302 
.br
 ezLCD-303 319 239
.br
 ezLCD-313 319 239
.br
 ezLCD-304 479 271
.br

