.TH "intro_widgets" 3 "Tue Jul 30 2013" "Version 1.02" "ezLCD Python Module" \" -*- nroff -*-
.ad l
.nh
.SH NAME
intro_widgets \- Introduction To Widgets 
.SH "Over View of Widgets"
.PP
text text
.br
 
.SH "Buttons"
.PP
Buttons Buttons everywhere
.br
 
.PP
  
.SH "TouchZone"
.PP
TouchZones work like buttons but do not display any graphics on their own
.br
 You have to supply the image\&.
.br
 So we can take the image below and can make 21 TouchZones one for each Emoticon
.br
   
.SH "Slider"
.PP
text text
.br
 
.SH "ProgressBar"
.PP
text text
.br
 
.SH "Gauge"
.PP
  
.PP
text text
.br
 
.SH "AnalogMeter"
.PP
  
.PP
text text
.br
 
.SH "DigitalMeter"
.PP
text text
.br
 
.SH "StaticText"
.PP
text text
.br
 
.SH "GroupBox"
.PP
text text
.br
 
.SH "Dial"
.PP
text text
.br
 
.SH "Choice"
.PP
text text
.br
 
.SH "CheckBox"
.PP
text text
.br
 
.SH "Radio Buttons"
.PP
text text
.br
 
