.TH "intro_themes" 3 "Tue Jul 30 2013" "Version 1.02" "ezLCD Python Module" \" -*- nroff -*-
.ad l
.nh
.SH NAME
intro_themes \- Introduction To Themes 
Themes will specify the colors used on widgets (buttons, sliders ect)
.br
 You can have 16 themes numbered 0-15\&. 
.br
   
.SH "Themes on Buttons"
.PP
  
.SH "Themes on Sliders"
.PP
  
.SH "Themes on Progress Bar"
.PP
  
